### ISSUE TITLE
given error 404 request resource not available

### ISSUE THREAD

**Issue by gajeravijayb** [ashishdoneriya/TransactionManager#1]
Hi Ashish

I take clone hall project from here and execute that project using my eclipse ide but its given me error like request resource not available.

I review web.xml file and on that given welcome file as index.html but index.html file is not available in webcontent folder. its in angular src folder. Can you please explain me how to configure welcome file in web.xml folder so its load my angular index.html file?

**Comment by ashishdoneriya** [comment]
1. You have to manually compile the code by executing `mvn clean install` in project directory. Then deploy the war file manually. `target/transactionManager-1.0.war`. It will not work when you run from eclipse.
2. index.html is in `angular/src/index.html` after complete compilation, it will be in the root of the war file and will be available. For more details please read [this article](https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwiBnIqwttDPAhUJs48KHQjnCo0QFggsMAI&url=http%3A%2F%2Fcsetutorials.com%2Fdeploy-angular-2-maven-webapp-on-tomcat.html&usg=AFQjCNH3wPKoRlnu60B8SeOJ1J7UWsF9jw&sig2=5HVvmbrYAD1X28qIw6Mawg)
